# version: "3.3"  yozish shart emas

# services:
#   timeless-next:
#     container_name: timeless-next
#     restart: always       # xatolik bersa qayta restart beradi.
#     image: node:20.10.0
#     ports:
#       - 4000:3000
#     environment:
#       - PORT=3000
#     volumes:
#       - ./:/usr/src/timeless-next
#     working_dir: /usr/src/timeless-next

#     networks:
#       - client-network

#     # FOR PRODUCTION
#     command: bash -c "yarn && yarn run build && yarn run start"

# networks:
#   client-network:
#     driver: bridge

services:
  timeless-next:
    container_name: timeless-next
    restart: always
    image: node:20.10.0
    ports:
      - 7000:3000
    environment:
      # - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1  # Disable Next.js telemetry
    volumes:
      - ./:/usr/src/timeless-next
    working_dir: /usr/src/timeless-next
    networks:
      - client-network
    command: bash -c "yarn install --frozen-lockfile && yarn build && yarn start"

networks:
  client-network:
    driver: bridge



# timeless-next:  localhost:4000 => container:3000
# timeless-api:   localhost:4001 => container:3002
# timeless-batch: localhost:4002 => container:3003
